#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: bookzone-example.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module bookzone-example.yang


class ns(object):
    hash = 475915277

    id = "http://example.com/ns/bookzone"

    uri = "http://example.com/ns/bookzone"

    prefix = "bz"

    bz_user_id = 1887414636
    bz_user_id_ = "user-id"
    bz_swedish = 6
    bz_swedish_ = "swedish"
    bz_moroccan_arabic = 4
    bz_moroccan_arabic_ = "moroccan-arabic"
    bz_swahili = 5
    bz_swahili_ = "swahili"
    bz_mp3 = 600067061
    bz_mp3_ = "mp3"
    bz_author = 2065757877
    bz_author_ = "author"
    bz_chinese = 1
    bz_chinese_ = "chinese"
    bz_arabic = 0
    bz_arabic_ = "arabic"
    bz_name = 1998270519
    bz_name_ = "name"
    bz_format = 1150348190
    bz_format_ = "format"
    bz_account_id = 769941472
    bz_account_id_ = "account-id"
    bz_english = 2
    bz_english_ = "english"
    bz_number_of_copies = 1899798051
    bz_number_of_copies_ = "number-of-copies"
    bz_shipping = 371527751
    bz_shipping_ = "shipping"
    bz_epub = 1593728501
    bz_epub_ = "epub"
    bz_paperback = 175393382
    bz_paperback_ = "paperback"
    bz_audio_cd = 183738742
    bz_audio_cd_ = "audio-cd"
    bz_hardcover = 1215090900
    bz_hardcover_ = "hardcover"
    bz_file_idty = 859280207
    bz_file_idty_ = "file-idty"
    bz_success = 87922769
    bz_success_ = "success"
    bz_purchase = 1214086146
    bz_purchase_ = "purchase"
    bz_authors = 515640059
    bz_authors_ = "authors"
    bz_format_id = 1467982273
    bz_format_id_ = "format-id"
    bz_outcome = 916548173
    bz_outcome_ = "outcome"
    bz_users = 987101583
    bz_users_ = "users"
    bz_books = 1509193799
    bz_books_ = "books"
    bz_delivery_url = 2031700144
    bz_delivery_url_ = "delivery-url"
    bz_language = 2034330531
    bz_language_ = "language"
    bz_user = 1529217067
    bz_user_ = "user"
    bz_format_idty = 399763516
    bz_format_idty_ = "format-idty"
    bz_isbn = 844277236
    bz_isbn_ = "isbn"
    bz_book = 607977079
    bz_book_ = "book"
    bz_pdf = 203178621
    bz_pdf_ = "pdf"
    bz_price = 1411576793
    bz_price_ = "price"
    bz_french = 3
    bz_french_ = "french"
    bz_title = 110890495
    bz_title_ = "title"
    bz_paper = 586200109
    bz_paper_ = "paper"
    bz_out_of_stock = 340994518
    bz_out_of_stock_ = "out-of-stock"
    bz_failure = 1833033127
    bz_failure_ = "failure"
    actionpoint_purchase = "purchase"
